name: Release

on:
  push:
    branches:
      - "main"

permissions:
    contents: write
    packages: write


jobs:
  get-next-version:
    name: Get next version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      hasNextVersion: ${{ steps.get-next-version.outputs.hasNextVersion }}
      version: ${{ steps.get-next-version.outputs.version }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - name: Get next version
        id: get-next-version
        uses: thenativeweb/get-next-version@2.7.1

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: get-next-version

    if: needs.get-next-version.outputs.hasNextVersion == 'true'

    steps:
      - name: Create new version
        run: |
          sed -i -r "s/(\/\/ @version[[:space:]]+)[0-9]+\.[0-9]+\.[0-9]+/\1${{ needs.get-next-version.outputs.version }}/" refresh-theme.user.js
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add refresh-theme.user.js
          git commit -m 'chore: Bump version to ${{ needs.get-next-version.outputs.version }}. [skip ci]'
          git push
          git tag ${{ needs.get-next-version.outputs.version }}
          git push origin ${{ needs.get-next-version.outputs.version }}